name: real_time_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  provider: 6.0.2
  pull_to_refresh: 2.0.0
  http: 0.13.4
  flutter_secure_storage: 5.0.2
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

